ghostty-copy-terminfo: Copy for root also
bin/ghostty-copy-terminfo: Copy the terminfo for the root user as well
we the current user, but allow that to fail. This helps with ncurses
commands which get run as root, such as `sudo journalctl -k` to view the
kernel log.

diff --git a/bin/ghostty-copy-terminfo b/bin/ghostty-copy-terminfo
--- a/bin/ghostty-copy-terminfo
+++ b/bin/ghostty-copy-terminfo
@@ -11,7 +11,10 @@ fi
 
 for remote in "$@"; do
     echo "Copying terminfo to ${remote}"
+    # Copy for the current user
     infocmp -x | ssh "${remote}" -- tic -x -
+    # Try to copy for root, but allow it to fail
+    infocmp -x | ssh "${remote}" -- sudo -n tic -x - || true
 done
 
 exit 0
