tmux: continued integration.
com.googlecode.iterm2.plist: Updated iTerm2 preferences.

tmux.conf: Enable clipboard mode and mouse integration.  The terminal-overrides to enable native scrolling comes from https://superuser.com/a/314620.

vim/plugins.vim: Add vim-tmux for syntax highlighting, K support for navigating to the tmux sub command in the tmux man page.

functions: Add tma() which attaches to the named session ($1) but first resizes the parent terminal to the same size as the session.  There is no support for passing additional options to tmux attach, but it would be easy to add.

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -44,3 +44,21 @@ set_title()
         echo -n "${ansititle}"
     fi
 }
+
+# tmux attach and resize parent terminal to match the target session
+tma()
+{
+  local session="$1"
+  details=$(tmux ls -F '#{session_name}:#{session_width}:#{session_height}' | grep -s "^$1:")
+  if [ -z "${details}" ] ; then 
+    echo "error: unknown session '${session}'" >&2
+    return
+  fi
+  local _session width height
+  IFS=: read _session width height <<< "${details}"
+  # add one line to allow for the tmux status bar
+  height=$(expr ${height} + 1)
+  local command="\033[8;${height};${width}t"
+  echo -ne "${command}"
+  tmux attach -t "${session}"
+}
